apiVersion: v2
name: guacamole
description: A Helm chart for Apache Guacamole with PostgreSQL
version: 0.1.0
appVersion: "1.6.0"
dependencies:
  - name: postgresql
    version: 12.5.7
    repository: https://charts.bitnami.com/bitnami