# Enable and configure internal PostgreSQL
postgresql:
  enabled: true
  auth:
    username: guacamole_user
    password: guacamole_pass
    database: guacamole_db
  fullnameOverride: guacamole-postgresql

# Guacamole application configuration
guacamole:
  image:
    repository: guacamole/guacamole
    tag: latest
  guacd:
    repository: guacamole/guacd
    tag: latest

  env:
    POSTGRES_HOSTNAME: guacamole-postgresql
    POSTGRES_DATABASE: guacamole_db
    POSTGRES_USER: guacamole_user
    POSTGRES_PASSWORD: guacamole_pass

  service:
    type: ClusterIP
    port: 8080

# Optional ingress
ingress:
  enabled: false

# Init job configuration (to init DB schema)
initdb:
  enabled: true
  image:
    repository: guacamole/guacamole
    tag: latest
  env:
    POSTGRES_HOSTNAME: guacamole-postgresql
    POSTGRES_DATABASE: guacamole_db
    POSTGRES_USER: guacamole_user
    POSTGRES_PASSWORD: guacamole_pass
