postgresql:
  enabled: true
  fullnameOverride: guacamole-postgresql
  auth:
    username: guacamole_user
    password: guacamole_pass
    database: guacamole_db
  primary:
    podAnnotations:
      "helm.sh/resource-policy": keep
    persistence:
      enabled: true
      size: 8Gi

guacamole:
  image:
    repository: guacamole/guacamole
    tag: latest
  guacd:
    repository: guacamole/guacd
    tag: latest
  env:
    POSTGRES_HOSTNAME: guacamole-postgresql
    POSTGRES_DATABASE: guacamole_db
    POSTGRES_USER: guacamole_user
    POSTGRES_PASSWORD: guacamole_pass
  service:
    type: ClusterIP
    port: 8080

initdb:
  enabled: true
  image:
    repository: guacamole/guacamole
    tag: latest
  env:
    POSTGRES_HOSTNAME: guacamole-postgresql
    POSTGRES_DATABASE: guacamole_db
    POSTGRES_USER: guacamole_user
    POSTGRES_PASSWORD: guacamole_pass
