image:
  repository: guacamole/guacamole
  tag: latest

guacd:
  repository: guacamole/guacd
  tag: latest

service:
  type: ClusterIP
  port: 8080

postgresql:
  enabled: true
  auth:
    postgresPassword: guacroot
    username: guacamole
    password: guacpass
    database: guacamole_db
