image:
  repository: guacamole/guacamole
  tag: latest

guacd:
  repository: guacamole/guacd
  tag: latest

service:
  type: ClusterIP
  port: 8080

postgresql:
  enabled: true
  fullnameOverride: guacamole-postgresql
  auth:
    postgresPassword: guacroot
    username: guacamole
    password: guacpass
    database: guacamole_db

  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 2Gi

env:
  POSTGRESQL_HOSTNAME: guacamole-postgresql
  POSTGRESQL_DATABASE: guacamole_db
  POSTGRESQL_USERNAME: guacamole
  POSTGRESQL_PASSWORD: guacpass
