postgresql:
  enabled: true
  fullnameOverride: guacamole-postgresql
  auth:
    username: guacamole_user
    password: guacamole_pass
    database: guacamole_db
  primary:
    podAnnotations:
      "helm.sh/resource-policy": keep
    persistence:
      enabled: true
      size: 8Gi

guacamole:
  image:
    repository: guacamole/guacamole
    tag: latest
  guacd:
    repository: guacamole/guacd
    tag: latest
  env:
    POSTGRES_HOSTNAME: guacamole-postgresql
    POSTGRES_DATABASE: guacamole_db
    POSTGRES_USER: guacamole_user
    POSTGRES_PASSWORD: guacamole_pass
  service:
    type: ClusterIP
    port: 8080

  # Inject OpenID env (static + from secret)
  extraEnv:
    - name: OPENID_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: guac-openid-secret
          key: openid-client-id
    - name: OPENID_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: guac-openid-secret
          key: openid-client-secret
    - name: OPENID_AUTHORIZATION_ENDPOINT
      value: https://github.com/login/oauth/authorize
    - name: OPENID_TOKEN_ENDPOINT
      value: https://github.com/login/oauth/access_token
    - name: OPENID_JWKS_ENDPOINT
      value: https://token.actions.githubusercontent.com/.well-known/jwks
    - name: OPENID_ISSUER
      value: https://token.actions.githubusercontent.com
    - name: OPENID_REDIRECT_URI
      value: https://guacamole.longhntraing.site/guacamole/api/ext/openid/callback

  extraVolumes:
    - name: guac-extensions
      emptyDir: {}

  extraVolumeMounts:
    - name: guac-extensions
      mountPath: /etc/guacamole/extensions

initdb:
  enabled: true
  image:
    repository: guacamole/guacamole
    tag: latest
  env:
    POSTGRES_HOSTNAME: guacamole-postgresql
    POSTGRES_DATABASE: guacamole_db
    POSTGRES_USER: guacamole_user
    POSTGRES_PASSWORD: guacamole_pass

externalSecrets:
  enabled: true
  name: guac-openid-secret
  targetSecret: guac-openid-secret
  secretStore:
    name: aws-ssm-store
    region: ap-southeast-1
    credentialsSecret: aws-ssm-creds
  parameters:
    clientID: /guacamole/openid-client-id
    clientSecret: /guacamole/openid-client-secret