# =====================
# PostgreSQL nội bộ
# =====================
postgresql:
  enabled: true
  fullnameOverride: guacamole-postgresql
  auth:
    username: guacamole_user
    password: guacamole_pass
    database: guacamole_db
  primary:
    podAnnotations:
      "helm.sh/resource-policy": keep
    persistence:
      enabled: true
      size: 8Gi

# =====================
# Guacamole core
# =====================
guacamole:
  image:
    repository: guacamole/guacamole
    tag: latest
  guacd:
    repository: guacamole/guacd
    tag: latest
  env:
    POSTGRES_HOSTNAME: guacamole-postgresql
    POSTGRES_DATABASE: guacamole_db
    POSTGRES_USER: guacamole_user
    POSTGRES_PASSWORD: guacamole_pass
  service:
    type: ClusterIP
    port: 8080

# =====================
# Init DB lần đầu
# =====================
initdb:
  enabled: true
  image:
    repository: guacamole/guacamole
    tag: latest
  env:
    POSTGRES_HOSTNAME: guacamole-postgresql
    POSTGRES_DATABASE: guacamole_db
    POSTGRES_USER: guacamole_user
    POSTGRES_PASSWORD: guacamole_pass

# =====================
# Mount plugin .jar OpenID qua initContainer
# =====================
extraVolumes:
  - name: guac-extensions
    emptyDir: {}

extraVolumeMounts:
  - name: guac-extensions
    mountPath: /etc/guacamole/extensions

extraInitContainers:
  - name: fetch-openid-plugin
    image: busybox
    command: [sh, -c]
    args:
      - >
        wget https://downloads.apache.org/guacamole/1.6.0/binary/guacamole-auth-sso-1.6.0.tar.gz -O /tmp/plugin.tar.gz &&
        tar -xzf /tmp/plugin.tar.gz -C /tmp &&
        cp /tmp/openid/guacamole-auth-sso-openid-1.6.0.jar /extensions/
    volumeMounts:
      - name: guac-extensions
        mountPath: /extensions

# =====================
# ENV từ secret external-secrets
# =====================
extraEnv:
  - name: OPENID_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: guac-openid-secret
        key: openid-client-id
  - name: OPENID_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: guac-openid-secret
        key: openid-client-secret

# =====================
# Cấu hình OpenID (GitHub)
# =====================
guacamoleProperties:
  openid-authorization-endpoint: https://github.com/login/oauth/authorize
  openid-token-endpoint: https://github.com/login/oauth/access_token
  openid-jwks-endpoint: https://token.actions.githubusercontent.com/.well-known/jwks
  openid-issuer: https://token.actions.githubusercontent.com
  openid-redirect-uri: https://guacamole.longhntraing.site/guacamole/api/ext/openid/callback

# =====================
# External Secrets integration (generate SecretStore + ExternalSecret từ Helm chart)
# =====================
externalSecrets:
  enabled: true

  name: guac-openid-secret
  targetSecret: guac-openid-secret

  secretStore:
    name: aws-ssm-store
    region: ap-southeast-1
    credentialsSecret: aws-ssm-creds

  parameters:
    clientID: /guacamole/openid-client-id
    clientSecret: /guacamole/openid-client-secret
