apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
data:
  guacamole.properties: |
    postgresql-hostname: ${POSTGRES_HOSTNAME}
    postgresql-port: 5432
    postgresql-database: ${POSTGRES_DATABASE}
    postgresql-username: ${POSTGRES_USER}
    postgresql-password: ${POSTGRES_PASSWORD}
