apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
data:
  guacamole.properties: |
    postgresql-hostname: {{ .Values.guacamole.env.POSTGRES_HOSTNAME }}
    postgresql-port: 5432
    postgresql-database: {{ .Values.guacamole.env.POSTGRES_DATABASE }}
    postgresql-username: {{ .Values.guacamole.env.POSTGRES_USER }}
    postgresql-password: {{ .Values.guacamole.env.POSTGRES_PASSWORD }}
    disable-authorization-notification: true
    disable-user-password-authentication: true
    openid-authorization-endpoint: {{ include "guacamole.envValue" (dict "name" "OPENID_AUTHORIZATION_ENDPOINT" "ctx" .) }}
    openid-token-endpoint:        {{ include "guacamole.envValue" (dict "name" "OPENID_TOKEN_ENDPOINT" "ctx" .) }}
    openid-jwks-endpoint:         {{ include "guacamole.envValue" (dict "name" "OPENID_JWKS_ENDPOINT" "ctx" .) }}
    openid-issuer:                {{ include "guacamole.envValue" (dict "name" "OPENID_ISSUER" "ctx" .) }}
    openid-redirect-uri:          {{ include "guacamole.envValue" (dict "name" "OPENID_REDIRECT_URI" "ctx" .) }}
    openid-username-claim-type:   preferred_username
    openid-groups-claim-type:     groups
