apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
data:
  guacamole.properties: |
    postgresql-hostname: guacamole-postgresql
    postgresql-port: 5432
    postgresql-database: guacamole_db
    postgresql-username: guacamole_user
    postgresql-password: guacamole_pass