apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
data:
  guacamole.properties: |
    postgresql-hostname: ${POSTGRES_HOSTNAME}
    postgresql-port: 5432
    postgresql-database: ${POSTGRES_DATABASE}
    postgresql-username: ${POSTGRES_USER}
    postgresql-password: ${POSTGRES_PASSWORD}
    disable-authorization-notification: true
    disable-user-password-authentication: true
    openid-authorization-endpoint: ${OPENID_AUTHORIZATION_ENDPOINT}
    openid-token-endpoint: ${OPENID_TOKEN_ENDPOINT}
    openid-jwks-endpoint: ${OPENID_JWKS_ENDPOINT}
    openid-issuer: ${OPENID_ISSUER}
    openid-client-id: ${OPENID_CLIENT_ID}
    openid-client-secret: ${OPENID_CLIENT_SECRET}
    openid-redirect-uri: ${OPENID_REDIRECT_URI}
    openid-username-claim-type: preferred_username
    openid-groups-claim-type: groups