apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
        - name: guacd
          image: {{ .Values.guacamole.guacd.repository }}:{{ .Values.guacamole.guacd.tag }}
          ports:
            - containerPort: 4822
        - name: guacamole
          image: {{ .Values.guacamole.image.repository }}:{{ .Values.guacamole.image.tag }}
          ports:
            - containerPort: 8080
          env:
            {{- range $key, $val := .Values.guacamole.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
          volumeMounts:
            - name: guacamole-config
              mountPath: /etc/guacamole/guacamole.properties
              subPath: guacamole.properties
      volumes:
        - name: guacamole-config
          configMap:
            name: guacamole-config
