apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  labels:
    app: guacamole
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              until nc -z {{ .Values.guacamole.env.POSTGRES_HOSTNAME }} 5432;
              do echo "Waiting for PostgreSQL..."; sleep 2; done
      containers:
        - name: guacd
          image: {{ .Values.guacamole.guacd.repository }}:{{ .Values.guacamole.guacd.tag }}
          ports:
            - containerPort: 4822

        - name: guacamole
          image: {{ .Values.guacamole.image.repository }}:{{ .Values.guacamole.image.tag }}
          ports:
            - containerPort: 8080
          env:
            {{- range $key, $val := .Values.guacamole.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
            {{- with .Values.guacamole.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: guacamole-config
              mountPath: /etc/guacamole/guacamole.properties
              subPath: guacamole.properties
            {{- with .Values.guacamole.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

      volumes:
        - name: guacamole-config
          configMap:
            name: guacamole-config
        {{- with .Values.guacamole.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}