{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshPolicy: "Periodic"
  refreshInterval: "1h"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.targetSecret }}
    creationPolicy: Owner
  data:
    - secretKey: openid-client-id
      remoteRef:
        key: {{ .Values.externalSecrets.parameters.clientID }}
    - secretKey: openid-client-secret
      remoteRef:
        key: {{ .Values.externalSecrets.parameters.clientSecret }}
{{- end }}
