apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-initdb
data:
  initdb.sql: |
    -- Your Guacamole SQL schema goes here
    -- (Bạn có thể lấy từ: https://github.com/apache/guacamole-server/tree/master/src/schema/postgresql)
