apiVersion: batch/v1
kind: Job
metadata:
  name: guacamole-initdb
spec:
  template:
    spec:
      containers:
        - name: initdb
          image: bitnami/postgresql:15
          command:
            - sh
            - -c
            - psql -h {{ .Values.guacamole.env.POSTGRES_HOSTNAME }} \
                  -U {{ .Values.guacamole.env.POSTGRES_USER }} \
                  -d {{ .Values.guacamole.env.POSTGRES_DATABASE }} \
                  -f /initdb/initdb.sql
          env:
            - name: PGPASSWORD
              value: {{ .Values.guacamole.env.POSTGRES_PASSWORD }}
          volumeMounts:
            - name: initdb-volume
              mountPath: /initdb
      volumes:
        - name: initdb-volume
          configMap:
            name: guacamole-initdb
      restartPolicy: OnFailure
  backoffLimit: 3
