apiVersion: batch/v1
kind: Job
metadata:
  name: guacamole-initdb
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: initdb
          image: {{ .Values.initdb.image.repository }}:{{ .Values.initdb.image.tag }}
          command:
            - sh
            - -c
            - >
              psql -h {{ .Values.initdb.env.POSTGRES_HOSTNAME }} \
                   -U {{ .Values.initdb.env.POSTGRES_USER }} \
                   -d {{ .Values.initdb.env.POSTGRES_DATABASE }} \
                   -f /initdb/initdb.sql
          env:
            - name: PGPASSWORD
              value: {{ .Values.initdb.env.POSTGRES_PASSWORD }}
          volumeMounts:
            - name: initdb-volume
              mountPath: /initdb
      volumes:
        - name: initdb-volume
          configMap:
            name: guacamole-initdb
      restartPolicy: OnFailure
  backoffLimit: 3
