{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.secretStore.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecrets.secretStore.credentialsSecret }}
            key: access-key
          secretAccessKeySecretRef:
            name: {{ .Values.externalSecrets.secretStore.credentialsSecret }}
            key: secret-access-key
{{- end }}
